### PR TITLE
Cannot execute as non-root user

### PR DESCRIPTION
**Pull request by ste-giraldo**
Hi, I can run monitoror as a root user without problems, but I prefer to run as a non privileged user, but despite I copied and changed the owner of the files: 
-rw-r--r-- 1 stefano stefano     1358 Jun 28 14:52 .env
-rw-r--r-- 1 stefano stefano     1520 Jun 28 15:02 config.json
-rwxr-xr-x 1 stefano stefano 20614027 Jun 27 15:32 monitoror 
I have the following error in the UI and I can't understand which variant I should enable. If I add "configVariant": "default" in the config.json I have another error.

Variant "default" is disabled for PING type. Check errors on the server side for the reason

ERROR_DISABLED_VARIANT

{
  "type": "PING",
  "label": "Google DNS - 8.8.8.8",
  "params": {
    "hostname": "8.8.8.8"
  },
  "configVariant": "default"
}

### CODE REVIEW

**Comment by Alex-D** [comment]
Hey!
First, you should create an issue, not a pull request.
Then, please read the note in the PING doc to run as non-root: https://monitoror.com/documentation/#ping
Finally, you do not need any configVariant in this context, just remove it.

**Comment by SamuelWitke** [comment]
Hey so just to confirm there is no way currently to run `PING` as a non-root user? 
From the note
Screen Shot 2021-12-09 at 1 04 55 PM

**Comment by ste-giraldo** [comment]
Just read the doc as the suggestion by Alex-D and everything worked.

**Comment by SamuelWitke** [comment]
> Just read the doc as the suggestion by Alex-D and everything worked.

Without having to launch as a super-user / non-root?

**Comment by ste-giraldo** [comment]
This is what I have.

Put monitoror in nologin (to remove the shell) in /etc/passwd:
`/home/monitoror:/usr/sbin/nologin`

Then load a bash for monitoror from another user and start it:
```
$ sudo -u monitoror bash
$ /home/monitoror/monitoror &
```

**Pull request closed without merging**
